export const story4 = {
  id: "story4",
  title: "The Squirrel and the Four Seasons",
  video: "-5kzhzzY4wg",
  file: "https://drive.google.com/file/d/1vP2j1c2ZLTN-GvMST4tFlI6Nz2DYok4y/view?usp=sharing",
  prelistening: [
    {
      id: "task1",
      title: "Nouns",
      type: "Look and say",
      dialogue: "I see a ...",
      images: [
    { url: "grass", label: "grass" },
    { url: "buds", label: "buds" },
    { url: "mushroom", label: "a mushroom" },
    { url: "apple", label: "a apple" },
    { url: "seeds", label: "seeds" },
    { url: "acorn", label: "an acorn" },
    { url: "hazelnut", label: "a hazelnut" },
    { url: "walnut", label: "a walnut" },
    { url: "pumpkin", label: "a pumpkin" },
  ],
    },
  ],
  pages: [
    {
      id: 1,
      altText: "squirrel in a tree",
      text: "We are in a forest. Hello, I am Nori. I am a squirrel. This is a big oak tree. I live in this tree. This is my home.",
    },
    {
      id: 2,
      altText: "squirrel and a mushroom",
      text: "It is spring now. In spring, the forest wakes up. Fresh grass grows under the oak tree. Soft buds grow on the branches. I eat fresh soft buds. I can find small mushrooms in the grass. I eat small mushrooms, too. But I don’t like them.",
    },
    {
      id: 3,
      altText: "squirrel and berry",
      text: "I also go to the river. I can find red berries by the river. Berries are sweet. I eat sweet red berries. “Spring food is fresh,” I say.",
    },
    {
      id: 4,
      altText: "squirrel and apple",
      text: "In summer, the days are warm and bright. Apples grow on thick branches on the apple-trees. Apples are big and sweet. I find apples and eat them. ",
    },
    {
      id: 5,
      altText: "squirrel and cherry",
      text: "Cherries grow on the thin branches on the cherry-trees. Cherries are small and sweet. I can eat them too. Strawberries grow in the grass. Strawberries are small and sweet. The grass is green and the strawberries are red. I find strawberries and eat them. “Summer food is sweet” I say.",
    },
    {
      id: 6,
      altText: "squirrel and walnut",
      text: "I like autumn. Trees are yellow and orange. Acorns grow on oaks. They are small and oval. I collect them for winter. Walnuts grow on bushes. They are small and round. I collect them for winter. Hazelnuts grow on trees. They are big and round. I collect them for winter. I can’t find pumpkins in the forest. Pumpkins grow on the farms. They are big and orange. I like pumpkins. I eat pumpkins and seeds in the pumpkins. I collect dry seeds. “Autumn food is good for winter,” I smile. I have food for the winter.",
    },
    {
      id: 7,
      altText: "squirrel in the nest",
      text: "I like winter. Winter is cold. The wind is strong and the snow is white. I am at home. But I can go out. There is no grass under the oak, there are no buds on the branches. There are no berries and there are no mushrooms. But I am ready. I have acorns, walnuts, hazelnuts and dry seeds at home.",
    },
    {
      id: 8,
      altText: "sqirrel on the snow",
      text: "I can find dry seeds and nuts under the snow. “Winter food is dry but good,” I say and smile.",
    },
  ],
  vocabulary: {
    nouns: [
      { word: "squirrel", meaning: "білка" },
      { word: "oak", meaning: "дуб" },
      { word: "seasons", meaning: "пори року" },
      { word: "spring", meaning: "весна" },
      { word: "summer", meaning: "літо" },
      { word: "autumn", meaning: "осінь" },
      { word: "winter", meaning: "зима" },
      { word: "days", meaning: "дні" },
      { word: "apples", meaning: "яблука" },
      { word: "cherries", meaning: "вишні" },
      { word: "acorns", meaning: "жолуді" },
      { word: "oaks", meaning: "дуби" },
      { word: "walnuts", meaning: "волоські горіхи" },
      { word: "hazelnuts", meaning: "фундук" },
      { word: "pumpkins", meaning: "гарбузи" },
      { word: "seeds", meaning: "насіння" },
      { word: "snow", meaning: "сніг" },
      { word: "nuts", meaning: "горіхи" },
    ],

    verbs: [
      { word: "live", meaning: "жити" },
      { word: "grows", meaning: "росте" },
      { word: "grow", meaning: "рости" },
      { word: "collect", meaning: "збирати" },
      { word: "like", meaning: "подобатися / любити" },
      { word: "smile", meaning: "усміхатися" },
      { word: "am", meaning: "є (форма дієслова to be)" },
      { word: "have", meaning: "мати" },
      { word: "find", meaning: "знаходити" },
    ],

    adjectives: [
      { word: "fresh", meaning: "свіжий" },
      { word: "sweet", meaning: "солодкий" },
      { word: "warm", meaning: "теплий" },
      { word: "bright", meaning: "яскравий" },
      { word: "thick", meaning: "густий / товстий" },
      { word: "thin", meaning: "тонкий" },
      { word: "yellow", meaning: "жовтий" },
      { word: "orange", meaning: "помаранчевий" },
      { word: "oval", meaning: "овальний" },
      { word: "round", meaning: "круглий" },
      { word: "dry", meaning: "сухий" },
      { word: "cold", meaning: "холодний" },
    ],

    adverbs: [
      { word: "now", meaning: "зараз" },
      { word: "too", meaning: "також / занадто" },
      { word: "also", meaning: "також" },
    ],

    prepositions: [
      { word: "under", meaning: "під" },
      { word: "by", meaning: "біля / поруч" },
      { word: "for", meaning: "для" },
      { word: "at", meaning: "у / при / біля" },
    ],
  },
  tasks: {
    task1: {
      name: "Clap if the food is from the forest.",
      list: ["acorns", "pumpkins", "hazelnuts", "apples", "seeds"],
    },
    task2: {
      name: "Repeat if true (clap if true)",
      list: [
        "In winter, grass grows.",
        "In autumn, trees are orange.",
        "In summer, days are cold.",
        "In spring, berries are sweet.",
      ],
    },
  },
  speaking: [
    {
      id: "task2",
      title: "Who lives in a nest?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "Who lives in a nest?" },
        { speaker: "B", line: "A magpie lives in a nest" },
      ],
      table: [
        {
          column1: [
            "Who",
            "A crow",
            "A boy",
            "A magpie",
            "A beaver",
            "A duck",
            "A squirrel",
            "An otter",
          ],
          column2: "lives",
          column3: "in",
          column4: ["a tree", "a nest", "a house", "a lodge", "a river"],
        },
      ],
      images: [
        { url: "nest", label: "a nest" },
        { url: "tree", label: "a tree" },
        { url: "lodge", label: "a lodge" },
        { url: "river", label: "a river" },
        { url: "house", label: "a house" },
        { url: "boy", label: "a boy" },
        { url: "puppy", label: "a puppy" },
        { url: "otter", label: "a otter" },
        { url: "magpie", label: "a magpie" },
        { url: "crow", label: "a crow" },
        { url: "duck", label: "a duck" },
        { url: "squirrel", label: "a squirrel" },
        { url: "beaver", label: "a beaver" },
      ],
    },
    {
      id: "task4",
      title: "What is this?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "What is this?" },
        { speaker: "B", line: "This is a pumpkin. Is it big?" },
        { speaker: "A", line: "Yes" },
      ],
      table: [
        {
          column1: "This",
          column2: "is",
          column3: ["a", "an"],
          column4: [
            "pumpkin",
            "mushroom",
            "apple",
            "acorn",
            "bud",
            "cherry",
            "hazelnut",
            "walnut",
            "seed",
          ],
        },
        {
          column1: "Is",
          column2: "it",
          column3: ["big", "small", "orange", "red", "brown", "white", "green"],
          column4: "?",
        },
      ],
      images: [
        { url: "pumpkin", label: "a pumpkin" },
        { url: "apple", label: "a apple" },
        { url: "mushroom", label: "a mushroom" },
        { url: "acorn", label: "a acorn" },
        { url: "seed", label: "a seed" },
        { url: "hazelnut", label: "a hazelnut" },
        { url: "walnut", label: "a walnut" },
        { url: "cherry", label: "a cherry" },
        { url: "bud", label: "a bud" },
      ],
    },
    {
      id: "task6",
      title: "A tree - trees",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "I see one tree." },
        { speaker: "B", line: "I see three trees." },
      ],
      table: [
        {
          column1: "I",
          column2: "see",
          column3: ["a", "an"],
          column4: [
            "tree",
            "trees",
            "pumpkin",
            "pumpkins",
            "walnut",
            "walnuts",
            "seed",
            "seeds",
            "apple",
            "apples",
            "bud",
            "buds",
          ],
          column5: "?",
        },
      ],
      images: [
        { url: "tree", label: "a tree" },
        { url: "pumpkin", label: "a pumpkin" },
        { url: "walnut", label: "a walnut" },
        { url: "apple", label: "a apple" },
        { url: "seed", label: "a seed" },
        { url: "bud", label: "a bud" },
        { url: "trees", label: "trees" },
        { url: "pumpkins", label: "pumpkins" },
        { url: "walnuts", label: "walnuts" },
        { url: "apples", label: "apples" },
        { url: "seeds", label: "seeds" },
        { url: "buds", label: "buds" },
      ],
    },
    {
      id: "task7",
      title: "How many trees?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "How many trees?" },
        { speaker: "B", line: "I see three trees." },
      ],
      table: [
        {
          column1: "How",
          column2: "many",
          column3: ["trees", "pumpkins", "walnuts", "seeds", "apples", "buds"],
          column4: "?",
        },
        {
          column1: "I",
          column2: "see",
          column3: ["a", "an"],
          column4: [
            "tree",
            "trees",
            "pumpkin",
            "pumpkin",
            "walnut",
            "walnut",
            "seed",
            "seeds",
            "apple",
            "apples",
            "bud",
            "buds",
          ],
        },
      ],
      images: [
        { url: "tree", label: "a tree" },
        { url: "pumpkin", label: "a pumpkin" },
        { url: "walnut", label: "a walnut" },
        { url: "apple", label: "a apple" },
        { url: "seed", label: "a seed" },
        { url: "bud", label: "a bud" },
        { url: "trees", label: "trees" },
        { url: "pumpkins", label: "pumpkins" },
        { url: "walnuts", label: "walnuts" },
        { url: "apples", label: "apples" },
        { url: "seeds", label: "seeds" },
        { url: "buds", label: "buds" },
      ],
    },
    {
      id: "task9",
      title: "What are these?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "What are these?" },
        { speaker: "B", line: "These are mushrooms." },
      ],
      table: [
        {
          column1: "These",
          column2: "are",
          column3: [
            "mushrooms",
            "pumpkins",
            "walnuts",
            "seeds",
            "cherries",
            "buds",
            "acorns",
          ],
          column4: "?",
        },
      ],
      images: [
        { url: "mushrooms", label: "mushrooms" },
        { url: "cherries", label: "cherries" },
        { url: "acorns", label: "acorns" },
        { url: "hazelnuts", label: "hazelnuts" },
        { url: "walnuts", label: "walnuts" },
        { url: "seeds", label: "seeds" },
        { url: "buds", label: "buds" },
        { url: "pumpkins", label: "pumpkins" },
      ],
    },
  ],
  games: [
    {
      url: "https://learningapps.org/watch?v=ptry3v5rc26",
    },
    { url: "https://learningapps.org/watch?v=pzjnqcwpa26" },
  ],
};
