export const story2 = {
  id: "story2",
  title: "Ben the Beaver and the River Friends",
  video: "JcvnXa2Gtzw",
  file: "https://drive.google.com/file/d/1qBOnENlQPyphkgj3p9LxcZfMDGNg--lh/view?usp=sharing",
  prelistening: [{
      id: "task1",
      title: "Nouns",
      type: "Look and say",
      dialogue: "I see a ...",
      images: [
    { url: "fox", label: "a fox" },
    { url: "otter", label: "an otter" },
    { url: "duck", label: "a duck" },
    { url: "fish", label: "a fish" },
    { url: "dam", label: "a dam" },
  ]
    },] ,
  pages: [
    {
      id: 1,
      imageURL: "/story_images/second_story/second_story_1.png",
      altText: "Ben the beaver",
      text: "Hello, it’s me, Ben the beaver. My fur is thick and brown. My tail is wide, and flat. My teeth are long and orange, and my eyes are small and black.",
    },
    {
      id: 2,
      imageURL: "/story_images/second_story/second_story_2.png",
      altText: "beaver lodge",
      text: "I live in a wooden lodge with my family. The lodge is near a wide river. My father is building a dam in the river.",
    },
    {
      id: 3,
      imageURL: "/story_images/second_story/second_story_3.png",
      altText: "beaver carries mud",
      text: "I have a friend. It is Molly the duck. She has white feathers and a yellow beak. She can catch small fish in the water.“Hello, Ben,” Molly says. “Hello, Molly” I say back. “I like the dam.” says Molly. “The deep water helps me swim safely.”",
    },
    {
      id: 4,
      imageURL: "/story_images/second_story/second_story_4.png",
      altText: "beaver carries branches",
      text: "Every morning, I wake up early. The river is calm and blue. Birds are singing in the trees. I swim to check the dam. The dam keeps the water deep and safe near our home.",
    },
    {
      id: 5,
      imageURL: "/story_images/second_story/second_story_5.png",
      altText: "baby beaver swimming",
      text: "On a rock by the river sits Oliver the otter. Oliver is my friend. He has small ears and a small nose. He has long thick tail. The tail helps him swim fast. He can catch fish and he can swim in  the water.“The dam keeps the river deep, thank you,” Oliver says.",
    },
    {
      id: 7,
      imageURL: "/story_images/second_story/second_story_7.png",
      altText: "baby beaver on the shore",
      text: "But not all animals are my friends.Red the fox is not my friend. He walks to the river.He has green eyes and a long red tail. He wants to cross the water. “The dam keeps the water deep. I can’t swim and I can’t go. I can’t cross the river here” he says. He is angry. I feel nervous, but I say:“This is our home. It keeps us safe.” The fox is angry, but he walks around the river.",
    },
    {
      id: 8,
      imageURL: "/story_images/second_story/second_story_8.png",
      altText: "beaver abd baby beaver",
      text: "The river is quiet again. The birds are happy. The ducks are happy. The otters are happy. I look at the strong dam and smile. The river is his home and it is a home for many animals.",
    },
  ],
  vocabulary: {
    nouns: [
      { word: "morning", meaning: "ранок" },
      { word: "tree", meaning: "дерево" },
      { word: "friend", meaning: "друг" },
      { word: "duck", meaning: "качка" },
      { word: "feather", meaning: "пір'їна" },
      { word: "beak", meaning: "дзьоб" },
      { word: "rock", meaning: "камінь" },
      { word: "otter", meaning: "видра" },
      { word: "fox", meaning: "лисиця" },
      { word: "home", meaning: "дім / домівка" },
      { word: "bird", meaning: "птах" },
    ],

    verbs: [
      { word: "wake up", meaning: "прокидатися" },
      { word: "sing", meaning: "співати" },
      { word: "check", meaning: "перевіряти" },
      { word: "keep", meaning: "зберігати / тримати" },
      { word: "catch", meaning: "ловити" },
      { word: "say", meaning: "сказати / казати" },
      { word: "walk", meaning: "йти пішки" },
      { word: "cross", meaning: "перетинати" },
      { word: "want", meaning: "хотіти" },
      { word: "feel", meaning: "відчувати" },
      { word: "help", meaning: "допомагати" },
      { word: "swim", meaning: "плавати" },
      { word: "look", meaning: "дивитися" },
      { word: "smile", meaning: "посміхатися" },
    ],

    adjectives: [
      { word: "thick", meaning: "товстий / густий" },
      { word: "wide", meaning: "широкий" },
      { word: "flat", meaning: "плоский" },
      { word: "long", meaning: "довгий" },
      { word: "calm", meaning: "спокійний" },
      { word: "quiet", meaning: "тихий" },
      { word: "wooden", meaning: "дерев'яний" },
      { word: "deep", meaning: "глибокий" },
      { word: "safe", meaning: "безпечний" },
      { word: "back", meaning: "задній / назад" },
      { word: "angry", meaning: "сердитий" },
    ],

    other: [
      { word: "every", meaning: "кожний" },
      { word: "early", meaning: "рано" },
      { word: "safely", meaning: "безпечно" },
      { word: "all", meaning: "всі / все" },
      { word: "around", meaning: "навколо" },
    ],
  },
  tasks: {
    task1: {
      name: "Who can say this",
      list: [
        "“I like the dam.” ",
        "“The dam keeps the river deep, thank you.”",
        "“I can’t cross the river here.”",
        "“This is our home. It keeps us safe.”",
      ],
    },
    task2: {
      name: "Say who can:",
      list: [
        "Who can catch small fish?",
        "Who can swim fast?",
        "Who cannot swim?",
        "Who builds the dam?",
        "Who checks the dam every morning?",
      ],
    },
    task3: {
      name: "Repeat if true (clap if true)",
      list: [
        "Ben has thin grey fur.",
        "Ben lives near a river.",
        "Ben’s father is building a dam.",
        "Molly has brown feathers.",
        "Oliver can swim.",
        "The fox is happy about the dam.",
        "The dam keeps the water deep.",
        "All animals are Ben’s friends.",
      ],
    },
    task4: {
      name: "Say who has:",
      list: [
        "white feathers and yellow beak",
        "long red tail and green eyes",
        "thick brown fur and flat tail",
        "long thick tail",
      ],
    },
  },
  speaking: [
    {
      id: "task2",
      title: "Who is this?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "Who is this?" },
        { speaker: "B", line: "This is a fox." },
      ],
      table: [
        {
          column1: "This",
          column2: "is",
          column3: ["a", "an"],
          column4: ["fox", "otter", "duck", "fish"],
        },
      ],
      images: [
        { url: "fox", label: "fox" },
        { url: "otter", label: "otter" },
        { url: "duck", label: "duck" },
        { url: "fish", label: "fish" },
      ],
    },
    {
      id: "task4",
      title: "Is he nervous?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "Is he nervous?" },
        { speaker: "B", line: "No. Is he calm?" },
      ],
      table: [
        {
          column1: "Is",
          column2: "he",
          column3: ["calm", "nervous"],
        },
      ],
      images: [
        { url: "calm1" },
        { url: "nervous1" },
        { url: "nervous2" },
        { url: "calm2" },
        { url: "nervous3" },
        { url: "nervous4" },
        { url: "nervous5" },
        { url: "nervous6" },
        { url: "calm4" },
        { url: "nervous7" },
        { url: "calm5" },
        { url: "nervous8" },
        { url: "nervous9" },
      ],
    },
    {
      id: "task6",
      title: "It has sharp teeth.",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "It has sharp teeth." },
        { speaker: "B", line: "A beaver. It has big ears." },
      ],
      table: [
        {
          column1: "It",
          column2: "has",
          column3: ["big", "small", "sharp", "wide", "flat", "long"],
          column4: ["teeth", "eyes", "nose", "ears", "tail", "head"],
        },
      ],
      images: [
        { url: "beaver", label: "beaver" },
        { url: "fox", label: "fox" },
        { url: "otter", label: "otter" },
      ],
    },
    {
      id: "task8",
      title: "It has sharp teeth.",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "What color is the house?" },
        { speaker: "B", line: "It is yellow and grey." },
      ],
      table: [
        {
          column1: "What color",
          column2: "is",
          column3: "the",
          column4: [
            "house",
            "tree",
            "river",
            "lodge",
            "fox",
            "otter",
            "duck",
            "fush",
          ],
        },
      ],
      images: [
        { url: "beaver", label: "beaver" },
        { url: "fox", label: "fox" },
        { url: "otter", label: "otter" },
      ],
    },
    {
      id: "task10",
      title: "Who has red tail?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "Who has red tail?" },
        { speaker: "B", line: "A fox has red tail" },
      ],
      table: [
        {
          column1: ["Who", "A fox", "A beaver", "An otter", "A duck"],
          column2: "has",
          column3: ["red", "brown", "grey", "white", "yellow"],
          column4: ["teeth", "eyes", "nose", "ears", "tail", "head", "beak"],
        },
      ],
      images: [
        { url: "beaver-head", label: "beaver head" },
        { url: "fox-head", label: "fox head" },
        { url: "otter-head", label: "otter head" },
        { url: "duck-head", label: "duck head" },
        { url: "beaver-tail", label: "beaver tail" },
        { url: "fox-tail", label: "fox tail" },
        { url: "otter-tail", label: "otter tail" },
        { url: "duck-tail", label: "duck tail" },
      ],
    },
  ],
  games: [
    {
      url: "https://learningapps.org/watch?v=p9ckdt21526",
    },
    { url: "https://learningapps.org/watch?v=pyde5z87326" },
  ],
};
