export const story3 = {
  id: "story3",
  title: "Bite and His Teeth",
  video: "N1QUq2HjWoo",
  file: "https://drive.google.com/file/d/1YRrPMLt3_Soq0TJ58Sm_dWE3KJowNIA9/view?usp=sharing",
  prelistening: [
    {
      id: "task1",
      title: "Nouns",
      type: "Look and say",
      dialogue: "I see a ...",
      images: [
    { url: "cow", label: "a cow" },
    { url: "pig", label: "a pig" },
    { url: "boy", label: "a boy" },
    { url: "wolf", label: "a wolf" },
    { url: "crow", label: "a crow" },
    { url: "puppy", label: "a puppy" },
    { url: "puddle", label: "a puddle" },
    { url: "tooth", label: "a tooth" },
    { url: "teeth", label: "teeth" },
  ],
    },
  ], 
    pages: [
    {
      id: 1,
      altText: "Little puppy",
      text: "This is Bite, the little puppy. He is small. His nose it wet. His eyes are big. His ears are droopy. His mouth is big and pink. There are no teeth in his mouth. He walks out of the house and sees a puddle. There is water in the puddle. It is wet. The puppy keeps walking. Then he says “Oh, my mouth… What is it? What is in my mouth?” ",
    },
    {
      id: 2,
      altText: "puppy and crow",
      text: "Bite the puppy meets a crow. It is big and old. It is black but its tummy is grey. Its beak is long. Bite says: “Look in my mouth. What can you see?” “I see a tooth in your mouth. The tooth is small and white.” says the crow. “What is tooth? What can I do with it?” “You can bite with it” says the crow and flies away.",
    },
    {
      id: 3,
      altText: "puppy and cow",
      text: "The puppy keeps walking and meets a cow. “Hello, Mrs. Cow” says the puppy “Do you have teeth?” The cow looks at the puppy and opens her mouth. There are big teeth in its mouth. “Do you like to bite?” asks the puppy. “No”, says the cow. “I don’t like to bite. Don’t bite, Bite!”",
    },
    {
      id: 4,
      altText: "puppy and pig",
      text: "The puppy keeps walking and meets a pig. “Hello, Mrs. Pig” says the puppy “Do you have teeth?” The pig stops eating and opens her mouth. There are small teeth in its mouth. “Can you bite?” says the puppy? “Yes, I can. But I don’t like to bite.” says the pig. “Don’t bite, Bite!”",
    },
    {
      id: 5,
      altText: "puppy and wolf",
      text: "Bite keeps walking and meets a wolf. “Hello” says Bite “Mr. Wolf, do you have teeth?” The wolf smiles. “Yes, little puppy, I have teeth” says the wolf. Bite can see sharp teeth. He is nervous. “Mr. Wolf!” says Bite “Can you bite?” “I can. But if you bite, others can bite you back. Don’t bite, Bite!” says the wolf and walks away.",
    },
    {
      id: 6,
      altText: "puppy and beaver",
      text: "Bite keeps walking and he sees a beaver. “Mr. Beaver” says Bite “You have big teeth. Do you like to bite?” “No, I don’t like to bite.” says beaver. “But you bite the tree” says Bite. “I don’t bite the tree, I cut it. I build a dam for my family and my friends. But I don’t bite. Don’t bite, Bite!”",
    },
    {
      id: 7,
      altText: "puppy and boy",
      text: "Bite keeps walking and meets a boy. “Hello, puppy” says the boy “What is your name?” “My name is Bite” says Bite. The boy is nervous. He looks at Bite and says: “Do you bite?” “No, I never bite!” says Bite. The boy and the puppy play together.",
    },
  ],
  vocabulary: {
    nouns: [
      { word: "bite", meaning: "укус" },
      { word: "puppy", meaning: "цуценя" },
      { word: "mouth", meaning: "рот" },
      { word: "teeth", meaning: "зуби" },
      { word: "tooth", meaning: "зуб" },
      { word: "house", meaning: "будинок" },
      { word: "puddle", meaning: "калюжа" },
      { word: "water", meaning: "вода" },
      { word: "crow", meaning: "ворона" },
      { word: "tummy", meaning: "животик" },
      { word: "beak", meaning: "дзьоб" },
      { word: "cow", meaning: "корова" },
      { word: "pig", meaning: "свиня" },
      { word: "wolf", meaning: "вовк" },
      { word: "others", meaning: "інші" },
      { word: "tree", meaning: "дерево" },
      { word: "boy", meaning: "хлопчик" },
      { word: "name", meaning: "ім'я" },
    ],

    verbs: [
      { word: "walk", meaning: "йти пішки" },
      { word: "keep", meaning: "тримати / зберігати" },
      { word: "see", meaning: "бачити" },
      { word: "say", meaning: "казати / сказати" },
      { word: "meet", meaning: "зустрічати" },
      { word: "look", meaning: "дивитися" },
      { word: "open", meaning: "відкривати" },
      { word: "like", meaning: "подобатися / любити" },
      { word: "bite", meaning: "кусати" },
      { word: "eat", meaning: "їсти" },
      { word: "smile", meaning: "посміхатися" },
      { word: "cut", meaning: "різати" },
      { word: "play", meaning: "гратися" },
    ],

    adjectives: [
      { word: "little", meaning: "маленький" },
      { word: "small", meaning: "малий" },
      { word: "wet", meaning: "мокрий" },
      { word: "big", meaning: "великий" },
      { word: "droopy", meaning: "обвислий" },
      { word: "pink", meaning: "рожевий" },
      { word: "purple", meaning: "фіолетовий" },
      { word: "old", meaning: "старий" },
      { word: "black", meaning: "чорний" },
      { word: "grey", meaning: "сірий" },
      { word: "long", meaning: "довгий" },
      { word: "white", meaning: "білий" },
      { word: "sharp", meaning: "гострий" },
      { word: "nervous", meaning: "нервовий / схвильований" },
    ],

    other: [
      { word: "then", meaning: "потім" },
      { word: "away", meaning: "геть / подалі" },
      { word: "back", meaning: "назад" },
      { word: "never", meaning: "ніколи" },
      { word: "together", meaning: "разом" },
      { word: "of", meaning: "з / від (родовий зв'язок)" },
      { word: "in", meaning: "в / у" },
      { word: "out", meaning: "назовні" },
      { word: "with", meaning: "з" },
      { word: "at", meaning: "біля / у / о" },
      { word: "for", meaning: "для / за" },
    ],
  },
  tasks: {
    task1: {
      name: "Repeat if true (clap if true)",
      list: [
        "The puppy is small.",
        "The crow is pink.",
        "The wolf has sharp teeth.",
        "The cow likes to bite.",
        "The beaver builds a dam.",
      ],
    },
    task2: {
      name: "Guess who:",
      list: [
        "“I am big and black. I can fly.”",
        "“I have sharp teeth. I can bite. My fur is grey”",
        "“I build a dam.”",
        "“I am small. My ears are droopy.”",
      ],
    },
  },
  speaking: [
    {
      id: "task2",
      title: "Is he young?",
      type: "Look and say",
      dialogue: [
        { speaker: "A", line: "Is he young?" },
        { speaker: "B", line: "Yes. Is he strong?" },
      ],
      table: [
        {
          column1: "Is",
          column2: ["he", "she"],
          column3: ["old", "young"],
        },
        {
          column1: ["He", "She"],
          column2: "has",
          column3: ["one", "many"],
          column4: ["tooth", "teeth"],
        },
      ],
      images: [
        { url: "old", label: "old" },
        { url: "big", label: "big" },
        { url: "small", label: "small" },
        { url: "strong", label: "strong" },
        { url: "careful", label: "careful" },
        { url: "fast", label: "fast" },
      ],
    },
    {
      id: "task4",
      title: "Who can fly?",
      type: "Look and say",
      dialogue: [
        { speaker: "A", line: "Who can fly?" },
        { speaker: "B", line: "A crow and a duck" },
      ],
      table: [
        {
          column1: "Who",
          column2: "can",
          column3: ["fly", "swim", "build", "collect", "bite"],
          column4: "?",
        },
      ],
      images: [
        { url: "otter", label: "an otter" },
        { url: "crow", label: "a crow" },
        { url: "puppy", label: "a puppy" },
        { url: "fox", label: "a fox" },
        { url: "wolf", label: "a wolf" },
        { url: "beaver", label: "a beaver" },
        { url: "boy", label: "a boy" },
        { url: "cow", label: "a cow" },
      ],
    },
    {
      id: "task5",
      title: "Can a crow swim?",
      type: "Look and say",
      dialogue: [
        { speaker: "A", line: "Can a crow swim?" },
        { speaker: "B", line: "No. Can an otter swim?" },
      ],
      table: [
        {
          column1: "Can",
          column2: ["a", "an"],
          column3: [
            "duck",
            "fox",
            "boy",
            "otter",
            "wolf",
            "beaver",
            "cow",
            "puppy",
          ],
          column4: ["fly", "swim", "build", "collect", "bite"],
          column5: "?",
        },
      ],
      images: [
        { url: "otter", label: "an otter" },
        { url: "crow", label: "a crow" },
        { url: "duck", label: "a duck" },
        { url: "puppy", label: "a puppy" },
        { url: "fox", label: "a fox" },
        { url: "wolf", label: "a wolf" },
        { url: "beaver", label: "a beaver" },
        { url: "boy", label: "a boy" },
        { url: "cow", label: "a cow" },
      ],
    },
    {
      id: "task7",
      title: "Who can fly?",
      type: "Look and say",
      dialogue: [
        { speaker: "A", line: "Who can fly?" },
        { speaker: "B", line: "A crow. Is it black?" },
        { speaker: "A", line: "Yes." },
      ],
      table: [
        {
          column1: "Who",
          column2: "can",
          column3: ["fly", "swim", "build", "collect", "bite"],
          column4: "?",
        },
        {
          column1: "Is",
          column2: ["it", "he"],
          column3: ["white", "black", "green", "brown", "grey"],
          column4: "?",
        },
      ],
      images: [
        { url: "crow", label: "a crow" },
        { url: "duck", label: "a duck" },
        { url: "puppy", label: "a puppy" },
        { url: "wolf", label: "a wolf" },
        { url: "beaver", label: "a beaver" },
        { url: "boy", label: "a boy" },
        { url: "cow", label: "a cow" },
      ],
    },
  ],
  games: [
    {
      url: "https://learningapps.org/watch?v=p7qx5m5pj26",
    },
    { url: "https://learningapps.org/watch?v=pbpnhffw326" },
  ],
};
