export const lesson4 = {
  id: "lesson4",
  title: "Hello, pets ...",
  video: ["pWepfJ-8XU0", "XM7Jnetdf0I"],
  prelistening: [
    {
      id: "task1",
      title: "Animals",
      type: "Look and say",
      images: [
        { url: "lion", label: "a lion" },
        { url: "camel", label: "a camel" },
        { url: "rabbit", label: "a rabbit" },
        { url: "fox", label: "a fox" },
        { url: "ladybug", label: "a ladybug" },
        { url: "ant", label: "an ant" },
        { url: "spider", label: "a spider" },
        { url: "lizard", label: "a lizard" },
        { url: "sloth", label: "a sloth" },
      ],
    },
    {
      id: "task2",
      title: "Parts",
      type: "Look and say",
      images: [
        { url: "hump", label: "a hump" },
        { url: "paw", label: "a paw" },
        { url: "spots", label: "spots" },
        { url: "legs", label: "legs" },
        { url: "stripes", label: "stripes" },
      ],
    },
    {
      id: "task3",
      title: "Watch out!",
      type: "Look and say",
      images: [
        { url: "mousemice", label: "one mouse - two mice" },
        { url: "fishfish", label: "one fish - two fish" },
        { url: "foxfoxes", label: "one fox - two foxes" },
      ],
    },
  ],
  pages: [
    {
      id: 1,
      altText: "A fox",
      text: "I see Annie. She is happy. She has four mice. One mouse is grey. One mouse is brown. Two mice are white.",
    },
    {
      id: 2,
      altText: "A fox",
      text: "Hello, I am Nick. I'm a fox. I am red. I have two green eyes. I have a black nose and black ears.",
    },
    
  ],
  vocabulary: {
    nouns: [
      { url: "lion", meaning: "лев" },
      { url: "camel", meaning: "верблюд" },
      { url: "rabbit", meaning: "кролик" },
      { url: "fox", meaning: "лис" },
      { url: "ladybug", meaning: "сонечко" },
      { url: "ant", meaning: "мураха" },
      { url: "spider", meaning: "павук" },
      { url: "lizard", meaning: "ящірка" },
      { url: "sloth", meaning: "лінивець" },
      { url: "hump", meaning: "горб" },
      { url: "paw", meaning: "лапа" },
      { url: "spot", meaning: "пляма" },
      { url: "leg", meaning: "нога" },
      { url: "stripe", meaning: "полоска" },
    ],
    verbs: [{ word: "say", meaning: "казати" }],
    phrases: [
      { word: "I have", meaning: "Я маю ..." },
      { word: "It is", meaning: "Він/вона є ..." },
    ],
  },
//   tasks: {
//     task1: {
//       name: "Say who:",
//       list: [
//         "Who is strong?",
//         "Who is fast?",
//         "Who is old?",
//         "Who is careful?",
//       ],
//     },
//   },
  speaking: [
    {
      id: "task1",
      title: "It is a camel.",
      type: "Look and say",
      dialogue: [{ speaker: "A", line: "It is a camel." }],
      table: [
        {
          column1: "It",
          column2: "is",
          column3: [
            "a camel",
            "a lion",
            "a rabbit",
            "a fox",
            "a sloth",
            "a spider",
            "a ant",
            "a ladybug",
          ],
        },
      ],
      question: "Who is it?",
      images: [
        { url: "camelbw", label: "a camel", answer: "It is a camel." },
        { url: "lionbw", label: "a lion", answer: "It is a lion." },
        { url: "rabbitbw", label: "a rabbit", answer: "It is a rabbit." },
        { url: "foxbw", label: "a fox", answer: "It is a fox." },
        { url: "slothbw", label: "a sloth", answer: "It is a sloth." },
        { url: "spiderbw", label: "a spider", answer: "It is a spider." },
        { url: "antbw", label: "a ant", answer: "It is an ant." },
        { url: "ladybugbw", label: "a ladybug", answer: "It is a ladybug." },
      ],
    },
    {
      id: "task2",
      title: "A camel is yellow.",
      type: "Look and say",
      dialogue: [{ speaker: "A", line: "A camel is yellow." }],
      table: [
        {
          column1: [
             "a camel",
            "a lion",
            "a rabbit",
            "a fox",
            "a sloth",
            "a spider",
            "a ant",
            "a ladybug",
          ],
          column2: "is",
          column3: ["black", "white", "grey", "blue", "red", "yellow", "brown"],
        },
      ],
      question: "What color is it?",
      images: [
        { url: "camel", label: "a camel", answer: "A camel is brown." },
        { url: "lion", label: "a lion", answer: "A camel is yellow." },
        { url: "rabbit", label: "a rabbit", answer: "A rabbit is white." },
        { url: "fox", label: "a fox", answer: "A fox is red." },
        { url: "sloth", label: "a sloth", answer: "A sloth is brown." },
        { url: "spider", label: "a spider", answer: "A spider is purple." },
        { url: "ant", label: "a ant", answer: "A ant is brown." },
        { url: "ladybug", label: "a ladybug", answer: "A ladybug is red." },
      ],
    },
    {
      id: "task3",
      title: "Two yellow camels.",
      type: "Look and say",
      dialogue: [{ speaker: "A", line: "Two yellow camels." }],
      table: [
        {column1: [
            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
          ],column2: ["black", "white", "grey", "blue", "red", "yellow", "brown"],
          column3: [
             "camel",
            "rabbit",
            "fox",
            "sloth",
            "spider",
            "ant",
            "ladybug",
          ],
          column4: "s"
          
        },
      ],
      question: "How many?",
      images: [
        { url: "sixcamels", label: "camels", answer: "Six yellow camels." },
        { url: "ninerabbits", label: "rabbits", answer: "Nine white rabbits." },
        { url: "fivefoxes", label: "foxes", answer: "Five red foxes." },
        { url: "twosloths", label: "sloths", answer: "Two brown sloths." },
        { url: "threespiders", label: "spiders", answer: "Three black spiders." },
        { url: "threeants", label: "ants", answer: "Three brown ants." },
        { url: "fourladybugs", label: "ladybugs", answer: "Four red ladybugs." },
      ],
    },
    {
      id: "task4",
      title: "He has a cat.",
      type: "Look and say",
      dialogue: [{ speaker: "A", line: "He has a cat." }],
      table: [
        {column1: [
            "he",
            "she",
          ],column2: "has",
          column3: [
             "a cat",
            "a dog",
            "a bird",
            "a mouse",
            "a fish",
            "a lion",
            "a robot",
            "a camel",
            "a rabbit",
            "an iguana",
          ],          
        },
      ],
      question: "What?",
      images: [
        { url: "shecat", label: "a cat", answer: "She has a cat." },
        { url: "hedog", label: "a dog", answer: "He has a dog." },
        { url: "hebird", label: "a bird", answer: "He has a bird." },
        { url: "hemouse", label: "a mouse", answer: "He has a mouse." },
        { url: "shefish", label: "a fish", answer: "She has a fish." },
        { url: "sheiguana", label: "an iguana", answer: "He has an iguana." },
        { url: "helion", label: "a lion", answer: "He has a lion." },
        { url: "herobot", label: "a robot", answer: "He has a robot." },
        { url: "hecamel", label: "a camel", answer: "He has a camel." },
        { url: "sherabbit", label: "a lizard", answer: "He has a lizard." },
        
      ],
    },
  ],
  games: [
    {
      url: "https://learningapps.org/watch?v=p2nf10qs226",
    },
  ],
};
