export const story7 = {
  id: "story7",
  title: "Peter the Pencil school week",
  video: "imCb4VFdPGY",
  file: "https://drive.google.com/file/d/1MTFS88SPLyEo5QiKCc7KLaEt1PVnCszn/view?usp=sharing",
  prelistening: [
    {
      id: "task1",
      title: "Nouns",
      type: "Look and say",
      dialogue: "I see a ...",
      images: [
        { url: "paper", label: "a paper" },
        { url: "pencil", label: "a pencil" },
        { url: "pencilBox", label: "a pencil box" },
        { url: "noteBook", label: "a notebook" },
        { url: "desk", label: "a desk" },
        { url: "sharpener", label: "a sharpener" },
        { url: "pen", label: "a pen" },
        { url: "ruler", label: "a ruler" },
      ],
    },
  ],
  pages: [
    {
      id: 1,
      altText: "pencil box",
      text: "Hello, I am Peter the Pencil. Look at me! I am new! I am long and grey. My nose is sharp. I live in a blue pencil box. There, I have many friends. Can you see Penny the pen? It is blue. That is Roo the ruler. It is long and yellow. And this is Shirley the sharpener. It helps me stay sharp.",
    },
    {
      id: 2,
      altText: "boy writes",
      text: "On Monday, I wake up early. The school starts. A boy puts me on his desk. I can see a big, wide notebook. It lies on the desk too. He takes me and writes letters in the notebook. I like to write. The letters are beautiful. Then he puts me back into the pencil box again.",
    },
    {
      id: 3,
      altText: "pencil and sharpener",
      text: "On Tuesday, the boy puts me on the desk again. He writes letters but they are not beautiful. My nose is not sharp. I can see Shirley the sharpener. “Hello, Peter!” says Shirley “How are you?” “I am not sharp” I say sadly. “Don’t be sad!” says the sharpener. “I will help you!” When my nose is sharp again, the boy erases old letters with my pink hat and writes new letters.",
    },
    {
      id: 4,
      altText: "pencil and ruler",
      text: "On Wednesday morning, I am on the desk again. I can see a maths book. There are numbers and shapes in it. I can see a triangle. Can I draw a triangle? I can, but I need help. I can see my friend Roo the ruler. “Hello, Peter the pencil!” says Roo “Are you happy to draw a triangle?” “Yes, I am” I say. We work together. What a nice triangle we draw. I write numbers. Then Ruth the ruler and I go back home – to the pencil box.",
    },
    {
      id: 5,
      altText: "picture of a house",
      text: "On Thursday, I can see some clouds in the sky. The boy turns on the lamp. It shines brightly. I can see a white paper. It is so big. I draw a square. Roo the ruler helps me again. Then we draw a triangle. We draw a small square inside the big square. I can see what it is. Can you? It is a house. I draw a round sun in the sky. Outside, it is raining but my sun is shining. I can see my brothers and sisters. They live in a big bright box. There are blue, red, yellow, green, black and brown pencil. They help me with my picture. The house is brown now. The triangle is red. It’s a roof. The sky is blue. The sun is yellow. The grass around the house is green.",
    },
    {
      id: 6,
      altText: "pencil and ruler under a desk",
      text: "On Friday, I fall under the desk! It is dark there. I can’t see my friends and I can’t see my boy. I am nervous and I am sad. What can I do? I lie under the desk and wait. Then I can hear Roo the ruler. “Peter the pencil!” she says “Where are you?” She is under the desk too. I can’t see her, but I can hear her. “I am here” I say. Roo helps me and we are outside again. We go back to our home – the pencil box. I am happy to see all my friends. “Hello, Penny the pen!” I say “Hello, Shirley the sharpener!” I am so happy.",
    },
    {
      id: 7,
      altText: "boy outside",
      text: "On Saturday, there is no school. I sleep in the pencil box. I dream about writing stories. I dream about drawing pictures. I dream about triangles and squares. On Sunday I wake up and I am outside. But where is the desk? I can see trees and bushes. They are yellow and red. The leaves are falling. I can see clouds in the sky. There is a big white paper and I draw the trees. I draw the bushes. My brothers and sisters are here too, so the picture is bright. It is beautiful. Shirley the sharpener helps me. It makes my nose sharp. Then we go back to the pencil box. “Tomorrow is Monday again,” I smile. “And I am ready for a new week!”",
    },
  ],
  vocabulary: {
    nouns: [
      { word: "pencil", meaning: "олівець" },
      { word: "eraser", meaning: "гумка" },
      { word: "pencil box", meaning: "пенал" },
      { word: "pen", meaning: "ручка" },
      { word: "ink", meaning: "чорнило" },
      { word: "ruler", meaning: "лінійка" },
      { word: "sharpener", meaning: "точилка" },
      { word: "notebook", meaning: "зошит" },
      { word: "maths book", meaning: "підручник з математики" },
      { word: "numbers", meaning: "числа" },
      { word: "shapes", meaning: "фігури" },
      { word: "triangle", meaning: "трикутник" },
      { word: "square", meaning: "квадрат" },
      { word: "roof", meaning: "дах" },
      { word: "paper", meaning: "папір" },
      { word: "lamp", meaning: "лампа" },
      { word: "desk", meaning: "парта / стіл" },
      { word: "letters", meaning: "літери" },
      { word: "picture", meaning: "малюнок" },
      { word: "clouds", meaning: "хмари" },
      { word: "sky", meaning: "небо" },
      { word: "grass", meaning: "трава" },
      { word: "trees", meaning: "дерева" },
      { word: "bushes", meaning: "кущі" },
      { word: "leaves", meaning: "листя" },
    ],
    verbs: [
      { word: "wake up", meaning: "прокидатися" },
      { word: "write", meaning: "писати" },
      { word: "erase", meaning: "витирати" },
      { word: "draw", meaning: "малювати" },
      { word: "help", meaning: "допомагати" },
      { word: "fall", meaning: "падати" },
      { word: "wait", meaning: "чекати" },
      { word: "hear", meaning: "чути" },
      { word: "sleep", meaning: "спати" },
      { word: "dream", meaning: "мріяти / бачити сон" },
      { word: "shine", meaning: "світити / сяяти" },
      { word: "live", meaning: "жити" },
      { word: "see", meaning: "бачити" },
      { word: "smile", meaning: "посміхатися" },
    ],
    adjectives: [
      { word: "new", meaning: "новий" },
      { word: "long", meaning: "довгий" },
      { word: "grey", meaning: "сірий" },
      { word: "sharp", meaning: "гострий" },
      { word: "big", meaning: "великий" },
      { word: "wide", meaning: "широкий" },
      { word: "beautiful", meaning: "гарний / красивий" },
      { word: "small", meaning: "малий / маленький" },
      { word: "bright", meaning: "яскравий" },
      { word: "dark", meaning: "темний" },
      { word: "happy", meaning: "щасливий" },
      { word: "sad", meaning: "сумний" },
      { word: "nervous", meaning: "схвильований / нервовий" },
    ],
  },
  tasks: {
    task1: {
      name: "Repeat if true (clap if true)",
      list: [
        "Peter is short.",
        "The ruler helps draw a triangle.",
        "On Friday Peter is happy under the desk.",
        "On Sunday Peter draws trees.",
        "Peter the pencil can write letters.",
        "Peter the pencil can build a lodge.",
        "Peter the pencil can sing in a tree.",
        "Peter the pencil can draw a square.",
        "Peter the pencil can sleep in a pencil box.",
        "Peter the pencil can find mushrooms.",
      ],
    },
    task2: {
      name: "Guess who:",
      list: [
        "“I am long and grey. I have a pink hat.” “I help draw triangles and squares.”",
        "“I help Peter the pencil to stay sharp.”",
        "“I am white. You can write in me”",
        "“I am home for pencils and pens, rulers and sharpeners.”",
      ],
    },
    task3: {
      name: "Act It Out(show, but don't say)",
      list: [
        "sharpen the pencil",
        "draw a triangle",
        "erase letters",
        "fall under the desk",
        "draw a big round sun",
      ],
    },
  },
  speaking: [
    {
      id: "task2",
      title: "What is he doing?",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "What is he doing?" },
        { speaker: "B", line: "He is swimming." },
      ],
      table: [
        {
          column1: "He",
          column2: "is",
          column3: [
            "swimming",
            "building",
            "collecting",
            "eating",
            "cutting",
            "sleeping",
          ],
        },
      ],
      images: [
        { url: "boySwim", label: "swimming" },
        { url: "boyBuild", label: "building" },
        { url: "boyCollect", label: "collecting" },
        { url: "boyEat", label: "eating" },
        { url: "boyCut", label: "cutting" },
        { url: "boySleep", label: "sleeping" },
      ],
    },
    {
      id: "task4",
      title: "This desk is bigger.",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "This desk is bigger." },
        { speaker: "B", line: "Yes. This paper is smaller." },
      ],
      table: [
        {
          column1: "This",
          column2: [
            "desk",
            "notebook",
            "paper",
            "sharpener",
            "duck",
            "cow",
            "pumpkin",
            "apple",
            "tree",
            "bush",
          ],
          column3: "is",
          column4: ["long", "short", "big", "small"],
          column5: "er.",
        },
      ],
      images: [
        { url: "deskNotebook", label: "a desk and a notebook" },
        { url: "paperSharpener", label: "a paper and a sharpener" },
        { url: "duckCow", label: "a duck and a cow" },
        { url: "pumpkinApple", label: "a pumpkin and a apple" },
        { url: "treeBush", label: "a tree and a bush" },
      ],
    },
    {
      id: "task5",
      title: "Pencil is longer",
      type: "Look and say.",
      dialogue: [
        { speaker: "A", line: "The pencil is longer." },
        { speaker: "B", line: "No. The ruler is shorter." },
      ],
      table: [
        {
          column1: [
            "The pencil",
            "The ruler",
            "the pen",
            "The pencil box",
            "The fox tail",
            "The beaver tail",
            "The leg",
            "The river",
            "The branch",
            "The carrot",
          ],
          column2: "is",
          column3: ["long", "short", "big", "small"],
          column4: "er.",
        },
      ],
      images: [
        { url: "pencilRuler", label: "a pencil and a ruler" },
        { url: "penPencilbox", label: "a pen and a pencil box" },
        { url: "foxBeaverTail", label: "a fox tail and a beaver tail" },
        { url: "legRiver", label: "a leg and a river" },
        { url: "branchCarrot", label: "a branch and a carrot" },
      ],
    },
  ],
  games: [
    { url: "https://learningapps.org/watch?v=poeefhv5326" },
    { url: "https://learningapps.org/watch?v=pk6vtcr5c26" },
    { url: "https://learningapps.org/watch?v=p690td1hn26" },
  ],
};
